# this is a template, isn't used by the docker-compose file. the productive file is mounted to ~/data/zigbee2mqtt
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyACM0
frontend: true
devices:
  ...
groups:
  ...