# PASSWORD env var has to be provided, e.g. with .env file
version: '3'
services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    network_mode: host
