- name: check if atuin is installed
  stat:
    path: /usr/bin/atuin
  register: atuin_installed

- name: Install atuin
  shell: bash <(curl https://raw.githubusercontent.com/ellie/atuin/main/install.sh)
  args:
    executable: /bin/bash
  when: not atuin_installed.stat.exists

- name: Bin atuin to zsh
  lineinfile:
    path: /home/{{ user }}/.zshrc
    line: eval "$(atuin init zsh)"
  when: not atuin_installed.stat.exists

# TODO shell completions
# atuin gen-completions --shell zsh --out-dir .
# sudo cp ~/tmp/_atuin . /usr/share/zsh/vendor-completions