- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: True

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: True

- name: install some system packages required for various stuff
  apt:
    pkg:
      - unzip
      - net-tools
#      - python3.10-venv
      - python3-venv
      - git
      - nano
      - curl
      - wget
    state: latest
  become: True

- name: git config user.name
  community.general.git_config:
    name: user.name
    value: Arkadius Schuchhardt
    scope: global

- name: git config user.email
  community.general.git_config:
    name: user.email
    value: arkadius@schuchhardt.com
    scope: global
