- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: True

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: True

- name: install some system packages required for various stuff
  apt:
    pkg:
      - unzip
      - net-tools
      - python3.10-venv
      - git
      - nano
      - curl
      - wget
    state: latest
  become: True
