- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: True

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: True

- name: install some system packages required for various stuff
  apt:
    pkg:
      - unzip
      - net-tools
#      - python3.10-venv
      - python3-venv
      - git
      - nano
      - curl
      - wget
    state: latest
  become: True

# TODO: replace with git config module https://docs.ansible.com/ansible/latest/collections/community/general/git_config_module.html
- name: git config user.name
  shell: git config --global user.name "Arkadius Schuchhardt"

- name: git config user.email
  shell: git config --global user.email "arkadius@schuchhardt.com"
