- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  become: True

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: True

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: True

- name: Update apt and install docker-ce
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: True

- name: install docker-compose
  apt:
    name: docker-compose
    state: latest
  become: True

- name: users | adding docker users (for use without sudo)
  user:
    name: "{{ user }}"
    append: yes
    groups: docker
  become: True

- name: add docker start to wsl.conf
  become: true
  blockinfile:
    path: /etc/wsl.conf
    block: |
      [boot]
      command="service docker start"
    create: yes
    insertbefore: BOF
