#
#        kubectl
#
## neuste Version
#
#cd ~/Downlaods
#
#curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#
#sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
#
## bestimmte Version
#
#cd ~/Downlaods
#
#curl -LO https://dl.k8s.io/release/v1.22.8/bin/linux/amd64/kubectl
#
#sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
#
#        helm
#
#wget https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz
#
#tar -xzf helm-v3.8.2-linux-amd64.tar.gz
#
#sudo mv linux-amd64/helm /usr/local/bin/helm
#
#        kubeseal
#
#wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/kubeseal-0.17.5-linux-amd64.tar.gz -O kubeseal.tar.gz
#
#tar -xzf kubeseal.tar.gz
#
#sudo install -m 755 kubeseal /usr/local/bin/kubeseal
#
#        k9s (https://k9scli.io/topics/install/) oder
#        lens
#
#
