- name: install dependencies
  become: true
  package:
    name:
      - zsh
      - git
    state: present

- name: clone oh-my-zsh for users
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: /home/{{ user }}
    creates: /home/{{ user }}/.oh-my-zsh

- name: set permissions of oh-my-zsh for users
  file:
    path: /home/{{ user }}/.oh-my-zsh
    mode: 'go-w'
    recurse: yes

- name: set default shell for users
  user:
    name: '{{ user }}'
    shell: /bin/zsh

- name: write .zshrc for users
  template:
    src: /home/{{ user}}/.oh-my-zsh/templates/zshrc.zsh-template
    dest: /home/{{ user }}/.zshrc
    backup: no
    mode: 'u=rw,go=r'
    force: no

- name: get current .zshrc plugins
  shell: cat .zshrc | sed -n -e 's/^plugins=(\(.*\))/\1/p'
  register: plugins_old
  changed_when: false

- name: determine plugins
  # removes duplicates
  shell: echo {{ (plugins_old.stdout | split(' ') + oh_my_zsh_plugins) | unique | select | join(' ') }}
  register: plugins_new
  changed_when: false

- name: add default plugins to .zshrc
  replace:
    path: /home/{{ user }}/.zshrc
    regexp: ^plugins=(.*)
    replace: plugins=({{ plugins_new.stdout }})
  changed_when: plugins_old.stdout != plugins_new.stdout

- name: add /home/{{ user }}/local/bin to PATH in .zshrc
  lineinfile:
    path: /home/{{ user }}/.zshrc
    line: 'export PATH=/home/arkadius/.local/bin:$PATH'
    insertafter: EOF

- name: zsh autosuggestions
  command: 'git clone https://github.com/zsh-users/zsh-autosuggestions /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
  args:
    chdir: /home/{{ user }}
    creates: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: add zsh-autosuggestions to .zshrc
  include_role:
    name: add_plugin_to_zshrc
  vars:
    new_plugin: zsh-autosuggestions

