# https://askubuntu.com/questions/1404129/ubuntu-22-04-lts-on-wsl-failed-to-retrieve-available-kernel-versions-failed
- name: Change needrestart config ob Ubuntu22.04 - kernelhints
  become: True
  replace:
    path: /etc/needrestart/needrestart.conf
    regexp: '.*\$nrconf{kernelhints}.*'
    replace: '$nrconf{kernelhints} = 0;'
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version']  == '22'

- name: Change needrestart config ob Ubuntu22.04 - ucodehints
  become: True
  replace:
    path: /etc/needrestart/needrestart.conf
    regexp: '.*\$nrconf{ucodehints}.*'
    replace: '$nrconf{ucodehints} = 0;'
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version']  == '22'