- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: True
  changed_when: false

- name: Install some wsl GUI stuff like xdg-open
  apt:
    name:
    - libfuse2
    - xdg-utils
    - libxrender1
    - libxtst6
    - libxi6
    - libasound2
    - libgbm-dev
    state: latest
  become: True

- name: set BROWSER env variable in zshrc
  lineinfile:
    path: '{{ item }}'
    line: export BROWSER="powershell.exe /C start"
  with_items:
    - '~/.profile'
    - '~/.bash_profile'
    - '~/.bashrc'
    - '~/.zprofile'
    - '~/.zshrc'
