- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: True

- name: Install aptitude
  apt:
    name:
    - libfuse2
    - xdg-utils
    state: latest
  become: True

- name: set BROWSER env variable in zshrc
  lineinfile:
    path: /home/{{ user }}/.zshrc
    line: export BROWSER="powershell.exe /C start"
