- name: check if zsh-autosuggestions in .zshrc
  shell: grep -x 'plugins=.*{{ new_plugin }}.*' /home/{{ user }}/.zshrc | cat
  register: zshrc_content
  changed_when: false

- name: add zsh-autosuggestions to .zshrc
  lineinfile:
    path: /home/{{ user }}/.zshrc
    regexp: 'plugins=\((.*)\)'
    line: 'plugins=(\1 {{ new_plugin }})'
    backrefs: yes
  when: zshrc_content.stdout == ""