- name: Update apt-get repo and cache
  apt:
    update_cache: true

- name: Install aptitude
  apt:
    name: aptitude
    state: latest

- name: install some system packages required for various stuff
  apt:
    name: install common packages
    pkg:
      - unzip
      - net-tools
      - python3.10-venv
      - git
      - nano
      - curl
      - wget
    state: latest
