version: '3.7'
services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
      args:
        REGISTRY: gitlab.office.auxmoney.com:4567
    volumes:
      - /usr/app/wheels
      - .:/usr/app
  prod:
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod
      args:
        REGISTRY: gitlab.office.auxmoney.com:4567

# docker-compose run dev poetry run black src --check
# docker-compose run dev poetry update
# docker-compose run --service-ports dev poetry run clv serve
# docker-compose build dev
# docker-compose up prod
