version: "3"
services:
  zigbee2mqtt:
      container_name: zigbee2mqtt
#      restart: unless-stopped
      image: koenkk/zigbee2mqtt
      volumes:
        - ./zigbee2mqtt/data:/app/data
        - /run/udev:/run/udev:ro
      ports:
        - 8080:8080
      environment:
        - TZ=Europe/Vienna
      devices:
        # Make sure this matched your adapter location
        - /dev/ttyUSB0:/dev/ttyACM0
#      network_mode: host
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
#    network_mode: host