[app]
loglevel = "DEBUG"
data_path = "data"
[[app.cities]]
    name = "Mülheim"
    gps_lat = 51.418568
    gps_lon = 6.884523

[weather_owm]
url_short = "http://api.openweathermap.org/data/2.5/weather"
url_complete = "http://api.openweathermap.org/data/2.5/onecall"
units = "metric"
api_key = ""

[weather_nmi]
url_short = "https://api.met.no/weatherapi/locationforecast/2.0/compact"
url_complete = "https://api.met.no/weatherapi/locationforecast/2.0/complete"

[s3]
bucket = "murkelhausen-weather"
aws_access_key_id = "AKIAYNIWNYJNLYTLAPGG"
aws_secret_access_key = ""
