loglevel = "DEBUG"
[[cities]]
    name = "Mülheim"
    gps_lat = 51.418568
    gps_lon = 6.884523

[weather_owm]
url = "http://api.openweathermap.org/data/2.5/onecall"
units = "metric"
api_key = ""

[weather_nmi]
url = "https://api.met.no/weatherapi/locationforecast/2.0/complete"
