- name: check if atuin is installed
  stat:
    path: /usr/bin/atuin
  register: atuin_installed

- name: Install atuin
  shell: bash <(curl https://raw.githubusercontent.com/ellie/atuin/main/install.sh)
  args:
    executable: /bin/bash
  when: not atuin_installed.stat.exists

- name: Bin atuin to zsh
  lineinfile:
    path: ~/.zshrc
    line: eval "$(atuin init zsh)"

- name: create atuin zsh completions
  command: atuin gen-completions -o /usr/share/zsh/vendor-completions --shell zsh
  become: true
  args:
    creates: /usr/share/zsh/vendor-completions/_atuin

- name: change atuin search to fulltext
  replace:
    path: ~/.config/atuin/config.toml
    regexp: "^(.*)search_mode(.*)$"
    replace: 'search_mode = "{{ atuin.search_mode }}"'

- name: change atuin db_path
  replace:
    path: ~/.config/atuin/config.toml
    regexp: "^(.*)db_path(.*)$"
    replace: 'db_path = "{{ atuin.db_path }}"'