- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: true
  changed_when: false

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: true

- name: install some system packages required for various stuff
  apt:
    pkg:
      - unzip
      - net-tools
      - python3-venv
      - nano
      - curl
      - wget
      - jq
      - graphviz  # for python diagrams
      - libmysqlclient-dev  # e.g. for airflow
      - libpq-dev  # e.g. for airflow
    state: latest
  become: True

- name: add ~/local/bin to PATH in .bashrc
  lineinfile:
    path: '{{ item }}'
    line: 'export PATH=~/.local/bin:$PATH'
    create: yes
    mode: 0644
    insertafter: EOF
  loop: '{{ source_files_bash }}'
