- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: true
  changed_when: false

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: true

- name: install some system packages required for various stuff
  apt:
    pkg:
      - unzip
      - net-tools
      - python3-venv
      - nano
      - curl
      - wget
    state: latest
  become: True
