- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: true
  changed_when: false

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
  become: true

- name: install some system packages required for various stuff
  apt:
    pkg:
      - unzip
      - net-tools
      - python3-venv
      - nano
      - curl
      - wget
      - zip
      - screen
      - graphviz  # for python diagrams
      - libmysqlclient-dev  # e.g. for airflow
      - libpq-dev  # e.g. for airflow
      - libsecret-1-0  # to store credentials e.g. for jetbrains products
      - gnome-keyring  # to store credentials e.g. for jetbrains products
    state: latest
  become: True

- name: add /home/{{ user }}/local/bin to PATH in .zshrc
  lineinfile:
    path: '{{ item }}'
    create: yes
    line: 'export PATH=/home/{{ user }}/.local/bin:$PATH'
  loop: '{{ source_files }}'
