- name: Add git repo
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: true
  become: True

- name: install some system packages required for various stuff
  apt:
    name: git
    state: latest
  become: True

- name: git config user.name
  community.general.git_config:
    name: user.name
    value: '{{ git.fullname }}'
    scope: global

- name: git config user.email
  community.general.git_config:
    name: user.email
    value: '{{ git.email }}'
    scope: global

- name: git config autocrlf
  community.general.git_config:
    name: core.autocrlf
    value: '{{ git.autocrlf }}'
    scope: global
