- name: Install PyCharm
  block:
    - name: PyCharm - Download and unarchive
      unarchive:
        src: https://download.jetbrains.com/python/pycharm-professional-{{ pycharm.version }}.tar.gz
        dest: /tmp
        creates: /tmp/pycharm-{{ pycharm.version }}/bin/pycharm.sh
        remote_src: yes

    - name: PyCharm - Copy to /opt
      become: true
      copy:
        src: /tmp/pycharm-{{ pycharm.version }}/
        dest: /opt/pycharm
        directory_mode: true
        remote_src: true

    - name: PyCharm - add symlink to /usr/local/bin
      become: true
      file:
        src: /opt/pycharm/bin/pycharm.sh
        dest: /usr/local/bin/pycharm.sh
        state: link
  when: pycharm.install == true

# TODO does not work
#    - name: PyCharm - create desktop link
#      become: true
#      copy:
#        dest: /usr/share/applications/pycharm.desktop
#        force: true
#        content: |
#          [Desktop Entry]
#          Type=Application
#          Name=PycharmUbuntu
#          Exec=/opt/pycharm/bin/pycharm.sh
#          Icon=/opt/pycharm/bin/pycharm.png

- name: Install Goland
  block:
    - name: Goland - Download and unarchive
      unarchive:
        src: https://download.jetbrains.com/go/goland-{{ goland.version }}.tar.gz
        dest: /tmp
        creates: /tmp/GoLand-{{ goland.version }}/bin/goland.sh
        remote_src: yes

    - name: Goland - Copy to /opt
      become: true
      copy:
        src: /tmp/GoLand-{{ goland.version }}/
        dest: /opt/goland
        directory_mode: true
        remote_src: true

    - name: Goland - add symlink to /usr/local/bin
      become: true
      file:
        src: /opt/goland/bin/goland.sh
        dest: /usr/local/bin/goland.sh
        state: link
  when: goland.install == true

# TODO does not work
#    - name: Goland - create desktop link
#      become: true
#      copy:
#        dest: /usr/share/applications/goland.desktop
#        force: true
#        content: |
#          [Desktop Entry]
#          Type=Application
#          Name=GolandUbuntu
#          Exec=/opt/goland/bin/goland.sh
#          Icon=/opt/goland/bin/goland.png

- name: Install DataGrip
  block:
    - name: DataGrip - Download and unarchive
      unarchive:
        src: https://download.jetbrains.com/datagrip/datagrip-{{ datagrip.version }}.tar.gz
        dest: /tmp
        creates: /tmp/DataGrip-{{ datagrip.version }}/bin/datagrip.sh
        remote_src: yes

    - name: DataGrip - Copy to /opt
      become: true
      copy:
        src: /tmp/DataGrip-{{ datagrip.version }}/
        dest: /opt/datagrip
        directory_mode: true
        remote_src: true

    - name: DataGrip - add symlink to /usr/local/bin
      become: true
      file:
        src: /opt/datagrip/bin/datagrip.sh
        dest: /usr/local/bin/datagrip.sh
        state: link
  when: datagrip.install == true

# TODO does not work
#    - name: DataGrip - create desktop link
#      become: true
#      copy:
#        dest: /usr/share/applications/datagrip.desktop
#        force: true
#        content: |
#          [Desktop Entry]
#          Type=Application
#          Name=DataGripUbuntu
#          Exec=/opt/datagrip/bin/datagrip.sh
#          Icon=/opt/datagrip/bin/datagrip.png
