- name: install dependencies
  become: true
  package:
    name:
      - zsh
      - git
    state: latest

- name: clone oh-my-zsh for users
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: '~'
    creates: '~/.oh-my-zsh'

- name: set permissions of oh-my-zsh for users
  file:
    path: '~/.oh-my-zsh'
    mode: 'go-w'
    recurse: yes

- name: set default shell for users
  become: true
  user:
    name: '{{ ansible_user_id }}'
    shell: '/bin/zsh'

- name: create .zshrc
  template:
    src: '~/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '~/.zshrc'
    backup: no
    mode: 'u=rw,go=r'
    force: no

- name: add ~/local/bin to PATH in .zshrc
  lineinfile:
    path: '{{ item }}'
    line: 'export PATH=~/.local/bin:$PATH'
    create: yes
    mode: 0644
    insertafter: EOF
  loop: '{{ source_files }}'

- name: get current .zshrc plugins
  shell: cat '~/.zshrc' | sed -n -e 's/^plugins=(\(.*\))/\1/p'
  register: plugins_old
  changed_when: false

- name: determine plugins
  # removes duplicates
  shell: echo {{ (plugins_old.stdout | split(' ') + oh_my_zsh.plugins) | unique | select | join(' ') }}
  register: plugins_new
  changed_when: false

- name: add default plugins to .zshrc
  replace:
    path: '~/.zshrc'
    regexp: ^plugins=(.*)
    replace: plugins=({{ plugins_new.stdout }})
  changed_when: plugins_old.stdout != plugins_new.stdout

- name: zsh autosuggestions
  command: 'git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
  args:
    chdir: '~'
    creates: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

- name: add zsh-autosuggestions to .zshrc
  include_role:
    name: add_plugin_to_zshrc
  vars:
    new_plugin: zsh-autosuggestions
  when: oh_my_zsh.install == true

- name: add ZSH_AUTOSUGGEST_STRATEGY to .zshrc
  lineinfile:
    path: '~/.zshrc'
    line: 'export ZSH_AUTOSUGGEST_STRATEGY=(history completion)'
    insertafter: EOF
