- name: Install prereq packages
  apt:
    update_cache: true
    pkg:
      - cmake
    state: latest
  become: True

- name: taskwarrior - get installed version
  shell: task --version | cat
  register: taskwarrior_version_installed
  changed_when: false

- name: install taskwarrior
  block:
    - name: taskwarrior - download & unarchive
      unarchive:
        src: https://github.com/GothenburgBitFactory/taskwarrior/releases/download/v{{ taskwarrior.version }}/task-{{ taskwarrior.version }}.tar.gz
        dest: /tmp
        remote_src: yes

    - name: taskwarrior - cmake
      shell: cmake -DCMAKE_BUILD_TYPE=release .
      args:
        chdir: /tmp/task-{{ taskwarrior.version }}
        executable: /bin/bash

    - name: taskwarrior - make
      make:
        chdir: /tmp/task-{{ taskwarrior.version }}

    - name: taskwarrior - make install
      make:
        chdir: /tmp/task-{{ taskwarrior.version }}
        target: install
      become: true
  when: taskwarrior_version_installed.stdout != taskwarrior.version

- name: taskwarrior - delete tmp folder
  file:
    path: /tmp/task-{{ taskwarrior.version }}
    state: absent

- name: taskwarrior - add oh-my-zsh plugin
  include_role:
    name: add_plugin_to_zshrc
  vars:
    new_plugin: taskwarrior
  when: oh_my_zsh.install == true

- name: create taskwarrior config
  copy:
    src: files/.taskrc
    dest: ~/.taskrc
    mode: 0644

- name: set taskwarrior directory in config
  replace:
    path: ~/.taskrc
    regexp: "^(.*)data.location(.*)$"
    replace: "data.location={{ taskwarrior.path }}"
