- name: Install prereq packages
  apt:
    update_cache: true
    pkg:
      - gnupg
      - software-properties-common
    state: latest
  become: True

- name: terraform - get installed version
  shell: terraform -version | head -n 1 | sed 's/Terraform\sv\([0-9.]*\)/\1/'
  register: terraform_version_installed
  changed_when: false

- name: install terraform
  block:
    - name: terraform - download & unarchive
      unarchive:
        src: https://releases.hashicorp.com/terraform/{{ terraform.version }}/terraform_{{ terraform.version }}_linux_amd64.zip
        dest: /tmp
        remote_src: yes

    - name: terraform - install to /usr/local/bin
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/terraform
        dest: /usr/local/bin/terraform
        mode: 0755
        owner: root
        group: root

    - name: terraform - delete tmp folder
      file:
        path: /tmp/terraform
        state: absent
  when: terraform_version_installed.stdout != terraform.version

- name: terraform - add oh-my-zsh plugin
  include_role:
    name: add_plugin_to_zshrc
  vars:
    new_plugin: terraform
  when: oh_my_zsh.install == true
