- name: Add WSL Utilities from PPA
  ansible.builtin.apt_repository:
    repo: ppa:wslutilities/wslu

- name: Update apt-get repo and cache
  apt:
    update_cache: true
  become: True
  changed_when: false

- name: Install some wsl GUI stuff like xdg-open
  apt:
    name:
    - ubuntu-wsl
    - wlsu
    - libfuse2
    - xdg-utils
    - libxrender1
    - libxtst6
    - libxi6
    - libasound2
    - libgbm-dev
    - libatk1.0-0  # pycharm
    - libcups2  # pycharm
    - libxdamage1  # pycharm
    - libatspi2.0-0  # pycharm
    - libpangocairo-1.0-0  # pycharm
    - libxkbcommon-x11-0  # pycharm
    - libatk-bridge2.0-0  # pycharm

    state: latest
  become: True

- name: set BROWSER env variable in zshrc
  lineinfile:
    path: '{{ item }}'
#    line: export BROWSER="powershell.exe /C start"
    line: export BROWSER=/usr/bin/wslview  # add sudo update-alternatives --config x-www-browser?
    create: yes
  with_items:
    - '/home/{{ user }}/.profile'
    - '/home/{{ user }}/.bash_profile'
    - '/home/{{ user }}/.bashrc'
    - '/home/{{ user }}/.zprofile'
    - '/home/{{ user }}/.zshrc'
