- name: Beowulf setup
  hosts: beowulf
  vars:
    docker_user: 'arkadius'
    user: 'arkadius'
    python:
      versions:
        - '3.10'
        - '3.9'
    oh_my_zsh:
      install: false
    source_files:
        - '/home/{{ user }}/.profile'
        - '/home/{{ user }}/.bash_profile'
        - '/home/{{ user }}/.bashrc'
  tasks:
    - name: Install common
      import_tasks: tasks/common.yml

    - name: Install pyenv + python
      import_tasks: tasks/python.yml

    - name: Install docker
      import_tasks: tasks/docker.yml

# confluent cli: curl -sL --http1.1 https://cnfl.io/cli | sh -s -- latest
# mosquitto cli: 