- name: Beowulf setup
  become: True
  hosts: beowulf
  vars:
    docker_user: 'arkadius'
  tasks:
    - name: Install common
      include_role:
        name: common

    - name: Install docker
      include_role:
        name: docker

