- name: Beowulf setup
  hosts: beowulf
  vars:
    docker_user: 'arkadius'
    user: 'arkadius'
    python:
      versions:
        - '3.10'
        - '3.9'
    source_files:
        - '/home/{{ user }}/.profile'
        - '/home/{{ user }}/.bashrc'
  tasks:
    - name: Install common
      import_tasks: tasks/common.yml

    - name: Install pyenv + python
      import_tasks: tasks/python.yml

    - name: Install docker
      import_tasks: tasks/docker.yml
