- name: My Ubuntu WSL setup
  hosts: localhost
  connection: local
  vars_files:
    - passwd.yml
  vars:
    fullname: Arkadius Schuchhardt
    email: arkadius@schuchhardt.com
    user: 'arkadius'
    pycharm_version: 2022.2.1
    goland_version: 2022.2.2
    datagrip_version: 2022.2.2
    kubectl_version: 1.22.8
    helm_version: 3.8.2
    kubeseal_version: 0.17.5
    oh_my_zsh_plugins:
      - git
      - python
      - pip
      - docker
      - docker-compose
      - ansible
      - ubuntu
      - rsync
#      - task-warrior
  tasks:
#    - name: Modify Ubuntu22.04 config
#      import_tasks: tasks/ubuntu22.04.yaml

    - name: Install homebrew
      import_tasks: tasks/homebrew.yml

#    - name: Install common
#      import_tasks: tasks/common.yaml
#
#    - name: Install git
#      import_tasks: tasks/git.yaml
#
#    - name: Install docker
#      import_tasks: tasks/docker.yaml
#
#    - name: Install zsh + oh_my_zsh
#      import_tasks: tasks/oh-my-zsh.yaml
#
#    - name: Install powerlevel10k theme
#      import_tasks: tasks/powerlevel10k.yaml
#
#    - name: setup WSL GUI stuff
#      import_tasks: tasks/wsl_gui.yaml
#
#    - name: Install atuin
#      import_tasks: tasks/atuin.yaml
#
#    - name: Install pyenv + python
#      import_tasks: tasks/python.yaml
#
#    - name: Install jetbrains products
#      import_tasks: tasks/jetbrains.yaml
#
#    - name: Install aws cli tool
#      import_tasks: tasks/aws.yaml

#    - name: Install k8s stuff
#      import_tasks: tasks/k8s.yml

