- name: My Ubuntu WSL setup
  become: True
  hosts: localhost
  connection: local
  vars:
    user: 'arkadius'
  tasks:
    - name: Install common
      include_role:
        name: common

    - name: Install docker
      include_role:
        name: docker

    - name: Install zsh + oh_my_zsh + powerlevel10k
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: arkadius
            oh_my_zsh:
              theme: robbyrussell
              plugins:
                - git
                - pip
                - pyenv
                - docker
                - docker-compose
                - task-warrior

    - name: .zshrc PATH
      lineinfile:
        path: /home/{{ user }}/.zshrc
        line: 'export PATH=/home/arkadius/.local/bin:$PATH'

    - name: zsh autosuggestions folder exists
      stat:
        path: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      register: zsh_autosuggestions_path

    - name: zsh autosuggestions
      command: 'git clone https://github.com/zsh-users/zsh-autosuggestions /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
      when: zsh_autosuggestions_path.stat.exists == false

    - name: check if zsh-autosuggestions in .zshrc
      command: grep -x 'plugins=.*zsh-autosuggestions.*' /home/{{ user }}/.zshrc
      register: zshrc_content

    - name: add zsh-autosuggestions to .zshrc
      lineinfile:
        path: /home/{{ user }}/.zshrc
        regexp: 'plugins=\((.*)\)'
        line: 'plugins=(\1 zsh-autosuggestions)'
      when: zshrc_content.stdout == ""
