- name: My Ubuntu WSL setup
  hosts: localhost
  connection: local
  vars_files:
    - passwd.yml
  vars:
    fullname: Arkadius Schuchhardt
    email: arkadius@schuchhardt.com
    user: 'arkadius'
    pycharm_version: 2022.2.1
    goland_version: 2022.2.2
    datagrip_version: 2022.2.2
    terraform_version: 1.2.9
    kubectl_version: 1.22.8
    helm_version: 3.8.2
    kubeseal_version: 0.17.5
    taskwarrior_version: 2.6.2
    oh_my_zsh_plugins:
      - git
      - python
      - pip
      - docker
      - docker-compose
      - ansible
      - ubuntu
      - rsync
  tasks:
    - name: Modify Ubuntu22.04 config
      import_tasks: tasks/ubuntu22.04.yml

    - name: Install homebrew
      import_tasks: tasks/homebrew.yml

    - name: Install common
      import_tasks: tasks/common.yml

    - name: Install git
      import_tasks: tasks/git.yml

    - name: Install docker
      import_tasks: tasks/docker.yml

    - name: Install zsh + oh_my_zsh
      import_tasks: tasks/oh-my-zsh.yml

    - name: Install powerlevel10k theme
      import_tasks: tasks/powerlevel10k.yml

    - name: setup WSL GUI stuff
      import_tasks: tasks/wsl_gui.yml

    - name: Install atuin
      import_tasks: tasks/atuin.yml

    - name: Install pyenv + python
      import_tasks: tasks/python.yml

    - name: Install jetbrains products
      import_tasks: tasks/jetbrains.yml

    - name: Install aws cli tool
      import_tasks: tasks/aws.yml

    - name: Install k8s stuff
      import_tasks: tasks/k8s.yml

    - name: Install terraform
      import_tasks: tasks/terraform.yml

    - name: Install taskwarrior
      import_tasks: tasks/taskwarrior.yml