- name: My Ubuntu WSL setup
  hosts: localhost
  connection: local
  vars:
    user: 'arkadius'
    fonts_path: /usr/share/fonts/TTF
  tasks:
    # https://askubuntu.com/questions/1404129/ubuntu-22-04-lts-on-wsl-failed-to-retrieve-available-kernel-versions-failed
    # TODO only for Ubuntu 22.04
    - name: Change needrestart config ob Ubuntu22.04 - kernelhints
      become: True
      replace:
        path: /etc/needrestart/needrestart.conf
        regexp: '.*\$nrconf{kernelhints}.*'
        replace: '$nrconf{kernelhints} = 0;'

    # TODO only for Ubuntu 22.04
    - name: Change needrestart config ob Ubuntu22.04 - ucodehints
      become: True
      replace:
        path: /etc/needrestart/needrestart.conf
        regexp: '.*\$nrconf{ucodehints}.*'
        replace: '$nrconf{ucodehints} = 0;'

    - name: Install common
      include_tasks: common.yaml

    - name: Install docker
      include_tasks: docker.yaml

    - name: Install zsh + oh_my_zsh
      include_tasks: oh-my-zsh.yaml

    - name: Install powerlevel10k theme
      include_tasks: powerlevel10k.yaml

    - name: Install atuin
      include_tasks: atuin.yaml

    - name: Install pyenv + python
      include_tasks: python.yaml
