- name: My Ubuntu WSL setup
  become: True
  hosts: localhost
  connection: local
  vars:
    docker_user: 'arkadius'
  tasks:
    - name: Install common
      include_role:
        name: common

    - name: Install docker
      include_role:
        name: docker

    - name: Install zsh + oh_my_zsh + powerlevel10k
      include_role:
        name: gantsign.oh-my-zsh
        users:
          - username: arkadius
            oh_my_zsh:
              theme: robbyrussell
              plugins:
                - git