app:
  debugMode: true
  modules:
    - kafkaProducer
    - scheduler
    - dispatcher
    - mqttConsumer
  queueChannelSize: 100
tasks:
  psutil:
    schedule: 60
mqtt:
  broker: "tcp://192.168.1.69:1883"
  clientId: gohausen
  cleanSession: false
  qos: 1
kafka:
  broker: 192.168.1.69:19092
  schemaRegistryUrl: http://192.168.1.69:8081
dispatcher:
  port: 8123
  shellyHTKafkaTopic: shelly_ht_sensor
  shellyFloodTopic: shelly_flood
  testTopic: testDispatcher
mappingMqttKafka:
  test:
    qos: 1
    mqttTopics:
      - test_topic
    kafkaTopic: test_topic
    payloadType: MQTTTestData
    debugMode: true
  xiaomi:
    qos: 1
    mqttTopics:
      - zigbee2mqtt/XiaomiTempCellarHobby
      - zigbee2mqtt/XiaomiTempCellarVersorgung
    kafkaTopic: xiaomi_mi_sensor
    payloadType: XiaomiMiSensorData
  aqara:
    qos: 1
    mqttTopics:
      - zigbee2mqtt/AqaraTemp1
      - zigbee2mqtt/AqaraTemp2
      - zigbee2mqtt/AqaraTemp3
    kafkaTopic: aqara_sensor
    payloadType: AqaraSensorData
  power:
    qos: 1
    mqttTopics:
      - tele/stromhaushalt/SENSOR
      - tele/stromwaermepumpe/SENSOR
    kafkaTopic: power_data
    payloadType: PowerData
    debugMode: true
