# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > get-poetry.py
        python get-poetry.py --version 1.1.6
        echo "PATH=${PATH}:${HOME}/.poetry/bin" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

  linting:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Lint with mypy
      run: |
        poetry run mypy src/
    - name: Lint with black
      run: |
        poetry run black src/ tests/

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Test with pytest
      run: |
        poetry run pytest tests/
